import Vue from 'vue';
import Provider from './Provider';
import FormatBold from './FormatBold';
import FormatItalic from './FormatItalic';
import FormatQuoteClose from './FormatQuoteClose';
import LinkVariant from './LinkVariant';
import FileImage from './FileImage';
import Table from './Table';
import FormatListNumbers from './FormatListNumbers';
import FormatListBulleted from './FormatListBulleted';
import FormatSize from './FormatSize';
import FormatStrikethrough from './FormatStrikethrough';
import StatusBar from './StatusBar';
import NavigationBar from './NavigationBar';
import SidePreview from './SidePreview';
import Eye from './Eye';
import Settings from './Settings';
import FilePlus from './FilePlus';
import FileMultiple from './FileMultiple';
import FolderPlus from './FolderPlus';
import Delete from './Delete';
import Close from './Close';
import Pen from './Pen';
import Target from './Target';
import ArrowLeft from './ArrowLeft';
import HelpCircle from './HelpCircle';
import Toc from './Toc';
import Login from './Login';
import Logout from './Logout';
import Sync from './Sync';
import SyncOff from './SyncOff';
import Upload from './Upload';
import ViewList from './ViewList';
import Download from './Download';
import CodeTags from './CodeTags';
import CodeBraces from './CodeBraces';
import OpenInNew from './OpenInNew';
import Information from './Information';
import Alert from './Alert';
import SignalOff from './SignalOff';
import Folder from './Folder';
import ScrollSync from './ScrollSync';
import Printer from './Printer';
import Undo from './Undo';
import Redo from './Redo';
import ContentSave from './ContentSave';
import Message from './Message';
import History from './History';
import Database from './Database';
import Magnify from './Magnify';
import FormatListChecks from './FormatListChecks';
import CheckCircle from './CheckCircle';
import ContentCopy from './ContentCopy';
import Key from './Key';
import DotsHorizontal from './DotsHorizontal';
import Seal from './Seal';

Vue.component('IconProvider', Provider);
Vue.component('IconFormatBold', FormatBold);
Vue.component('IconFormatItalic', FormatItalic);
Vue.component('IconFormatQuoteClose', FormatQuoteClose);
Vue.component('IconLinkVariant', LinkVariant);
Vue.component('IconFileImage', FileImage);
Vue.component('IconTable', Table);
Vue.component('IconFormatListNumbers', FormatListNumbers);
Vue.component('IconFormatListBulleted', FormatListBulleted);
Vue.component('IconFormatSize', FormatSize);
Vue.component('IconFormatStrikethrough', FormatStrikethrough);
Vue.component('IconStatusBar', StatusBar);
Vue.component('IconNavigationBar', NavigationBar);
Vue.component('IconSidePreview', SidePreview);
Vue.component('IconEye', Eye);
Vue.component('IconSettings', Settings);
Vue.component('IconFilePlus', FilePlus);
Vue.component('IconFileMultiple', FileMultiple);
Vue.component('IconFolderPlus', FolderPlus);
Vue.component('IconDelete', Delete);
Vue.component('IconClose', Close);
Vue.component('IconPen', Pen);
Vue.component('IconTarget', Target);
Vue.component('IconArrowLeft', ArrowLeft);
Vue.component('IconHelpCircle', HelpCircle);
Vue.component('IconToc', Toc);
Vue.component('IconLogin', Login);
Vue.component('IconLogout', Logout);
Vue.component('IconSync', Sync);
Vue.component('IconSyncOff', SyncOff);
Vue.component('IconUpload', Upload);
Vue.component('IconViewList', ViewList);
Vue.component('IconDownload', Download);
Vue.component('IconCodeTags', CodeTags);
Vue.component('IconCodeBraces', CodeBraces);
Vue.component('IconOpenInNew', OpenInNew);
Vue.component('IconInformation', Information);
Vue.component('IconAlert', Alert);
Vue.component('IconSignalOff', SignalOff);
Vue.component('IconFolder', Folder);
Vue.component('IconScrollSync', ScrollSync);
Vue.component('IconPrinter', Printer);
Vue.component('IconUndo', Undo);
Vue.component('IconRedo', Redo);
Vue.component('IconContentSave', ContentSave);
Vue.component('IconMessage', Message);
Vue.component('IconHistory', History);
Vue.component('IconDatabase', Database);
Vue.component('IconMagnify', Magnify);
Vue.component('IconFormatListChecks', FormatListChecks);
Vue.component('IconCheckCircle', CheckCircle);
Vue.component('IconContentCopy', ContentCopy);
Vue.component('IconKey', Key);
Vue.component('IconDotsHorizontal', DotsHorizontal);
Vue.component('IconSeal', Seal);
